python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-4  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-4  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-4  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-4  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-4  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-4  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-4  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-4  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-4  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-3  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-3  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-3  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-3  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-3  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-3  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-3  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-3  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-3  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-2  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-2  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-2  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-2  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-2  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-2  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-2  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-2  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-2  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-1  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-1  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-1  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-1  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-1  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-1  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-1  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-1  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=-1  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=0  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=0  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=0  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=0  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=0  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=0  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=0  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=0  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=0  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=1  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=1  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=1  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=1  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=1  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=1  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=1  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=1  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=1  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=2  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=2  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=2  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=2  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=2  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=2  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=2  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=2  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=2  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=3  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=3  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=3  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=3  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=3  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=3  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=3  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=3  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=3  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=4  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=4  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=4  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=4  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=4  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=4  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=4  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=4  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job _temp_dir --offset1=4  --offset2=4 
