
REWARDCLASSES = {
    "Breakout": "Human Optimal",
    "Pong": "Human Optimal",
    "SpaceInvaders": "Human Optimal",
    "MsPacman": "Dense",
    "Qbert": "Dense",
    "BankHeist": "Dense",
    "MontezumaRevenge": "Sparse",
    "Pitfall": "Sparse",
    "Venture": "Sparse",
    "Freeway": "Sparse",
    "PrivateEye": "Sparse",
    "Solaris": "Sparse",
}

ENVCLASSES = {
    "Breakout": "Atari",
    "Pong": "Atari",
    "SpaceInvaders": "Atari",
    "MsPacman": "Atari",
    "Qbert": "Atari",
    "BankHeist": "Atari",
    "MontezumaRevenge": "Atari",
    "Pitfall": "Atari",
    "Venture": "Atari",
    "Freeway": "Atari",
    "PrivateEye": "Atari",
    "Solaris": "Atari",
    "Acrobot": "Classic Control",
    "Cartpole": "Classic Control",
    "MountainCar": "Classic Control",
    "MountainCarContinuous": "Classic Control",
    "Pendulum": "Classic Control",
    "Ant": "Mujoco",
    "HalfCheetah": "Mujoco",
    "Hopper": "Mujoco",
    "Humanoid": "Mujoco",
    "HumanoidStandup": "Mujoco",
    "InvertedDoublePendulum": "Mujoco",
    "InvertedPendulum": "Mujoco",
    "Reacher": "Mujoco",
    "Swimmer": "Mujoco",
    "Walker2d": "Mujoco",
}

KEYNAMES = {
    "episode_rewards": "Mean Episodic Reward",
    "episode_std_rewards": "Episodic Reward Standard Deviation",
    "episode_stderr_rewards": "Episodic Reward Standard Error",
    "episode_value_ests": "Mean Episodic Value Estimates",
    "episode_values": "Mean Episodic Values",
    "episode_td_err": "Mean Episodic TD Error",
    "episode_avg_len": "Mean Episode Length",
    "episode_std_avg_len": "Episode Length Standard Deviation",
    "step_rewards": "Mean Reward per Step",
    "step_value_ests": "Mean Value Estimates per Step",
    "step_values": "Mean Values per Step",
    "step_td_err": "Mean TD Error per Step",
}
