
REWARDCLASSES = {
    "Breakout": "Human Optimal",
    "Pong": "Human Optimal",
    "SpaceInvaders": "Human Optimal",
    "MsPacman": "Dense",
    "Qbert": "Dense",
    "BankHeist": "Dense",
    "MontezumaRevenge": "Sparse",
    "Pitfall": "Sparse",
    "Venture": "Sparse",
    "Freeway": "Sparse",
    "PrivateEye": "Sparse",
    "Solaris": "Sparse",
}

ENVCLASSES = {
    "Breakout": "Atari",
    "Pong": "Atari",
    "SpaceInvaders": "Atari",
    "MsPacman": "Atari",
    "Qbert": "Atari",
    "BankHeist": "Atari",
    "MontezumaRevenge": "Atari",
    "Pitfall": "Atari",
    "Venture": "Atari",
    "Freeway": "Atari",
    "PrivateEye": "Atari",
    "Solaris": "Atari",
    "Acrobot-v1": "Classic Control",
    "Cartpole-v1": "Classic Control",
    "MountainCar-v0": "Classic Control",
    "MountainCarContinuous-v0": "Classic Control",
    "Pendulum-v0": "Classic Control",
    "Ant-v2": "Mujoco",
    "HalfCheetah-v2": "Mujoco",
    "Hopper-v2": "Mujoco",
    "Humanoid-v2": "Mujoco",
    "HumanoidStandup-v2": "Mujoco",
    "InvertedDoublePendulum-v2": "Mujoco",
    "InvertedPendulum-v2": "Mujoco",
    "Reacher-v2": "Mujoco",
    "Swimmer-v2": "Mujoco",
    "Walker2d-v2": "Mujoco",
}
