
REWARDCLASSES = {
    "Breakout": "Human Optimal",
    "Pong": "Human Optimal",
    "SpaceInvaders": "Human Optimal",
    "MsPacman": "Dense",
    "Qbert": "Dense",
    "BankHeist": "Dense",
    "MontezumaRevenge": "Sparse",
    "Pitfall": "Sparse",
    "Venture": "Sparse",
    "Freeway": "Sparse",
    "PrivateEye": "Sparse",
    "Solaris": "Sparse",
}

ENVCLASSES = {
    "Breakout": "Atari",
    "Pong": "Atari",
    "SpaceInvaders": "Atari",
    "MsPacman": "Atari",
    "Qbert": "Atari",
    "BankHeist": "Atari",
    "MontezumaRevenge": "Atari",
    "Pitfall": "Atari",
    "Venture": "Atari",
    "Freeway": "Atari",
    "PrivateEye": "Atari",
    "Solaris": "Atari",
    "Acrobot-v1": "Classic Control",
    "Cartpole-v1": "Classic Control",
    "MountainCar": "Classic Control",
    "MountainCarContinuous": "Classic Control",
    "Pendulum": "Classic Control",
    "Ant": "Mujoco",
    "HalfCheetah": "Mujoco",
    "Hopper": "Mujoco",
    "Humanoid": "Mujoco",
    "HumanoidStandup": "Mujoco",
    "InvertedDoublePendulum": "Mujoco",
    "InvertedPendulum": "Mujoco",
    "Reacher": "Mujoco",
    "Swimmer": "Mujoco",
    "Walker2d": "Mujoco",
}
