python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-15  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-14  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-13  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-12  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-11  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-10  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-9  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-8  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-7  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-6  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-5  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-4  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-3  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-2  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=-1  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=0  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=1  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=2  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=3  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=4  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=5  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=6  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=7  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=8  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=9  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=10  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=11  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=12  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=13  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=14  --offset2=15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-15 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=-1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=0 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=1 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=2 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=3 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=4 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=5 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=6 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=7 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=8 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=9 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=10 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=11 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=12 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=13 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=14 
python -m reward_surfaces.bin.eval_plane_job hopper_eig_vecs_plane --offset1=15  --offset2=15 
